name: Create WordPress Plugin Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.0.1)"
        required: true
        default: "1.0.1"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create distribution directory
        run: mkdir -p dist/network-site-details

      - name: Copy plugin files
        run: |
          cp -r assets dist/network-site-details/
          cp -r vendor dist/network-site-details/
          cp network-site-details.php dist/network-site-details/
          cp README.txt dist/network-site-details/
          cp composer.json dist/network-site-details/

      - name: Clean vendor directory based on .distignore and WP.org rules
        run: |
          cd dist/network-site-details

          # Remove forbidden files and files with spaces
          find vendor -name "*.md" -delete
          find vendor -name "*LICENSE*" -delete
          find vendor -name "*CHANGELOG*" -delete
          find vendor -name "*README*" -delete
          find vendor -name "*.xml" -delete
          find vendor -name "*.dist" -delete
          find vendor -name "*.yml" -delete
          find vendor -name "*.yaml" -delete
          find vendor -name "*.neon" -delete
          find vendor -name "*.cnf" -delete
          find vendor -name "*.tool-versions" -delete
          find vendor -name "*.sarif" -delete
          find vendor -name "*.bat" -delete
          find vendor -name "*.sh" -delete
          find vendor -name "*.xlsx" -delete
          find vendor -name "*.xls" -delete
          find vendor -name "*.csv" -delete
          find vendor -type f -name "* *" -delete

          # Remove test and example directories
          find vendor -type d -name "*test*" -exec rm -rf {} + 2>/dev/null || true
          find vendor -type d -name "*docs*" -exec rm -rf {} + 2>/dev/null || true
          find vendor -type d -name "*examples*" -exec rm -rf {} + 2>/dev/null || true
          find vendor -type d -name "*guides*" -exec rm -rf {} + 2>/dev/null || true
          find vendor -type d -name ".github" -exec rm -rf {} + 2>/dev/null || true

          # Remove bin directory
          rm -rf vendor/bin 2>/dev/null || true

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r ../network-site-details-${{ github.event.inputs.version || github.ref_name }}.zip network-site-details/

      - name: Get file size
        id: filesize
        run: |
          SIZE=$(ls -lh network-site-details-*.zip | awk '{print $5}')
          echo "size=$SIZE" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Network Site Details ${{ github.event.inputs.version || github.ref_name }}
          body: |
            ## WordPress Plugin Release 🚀

            **Network Site Details** - Version ${{ github.event.inputs.version || github.ref_name }}

            ### 📦 What's Included:
            - ✅ All plugin files ready for WordPress installation
            - ✅ Optimized vendor directory (production dependencies only)
            - ✅ File size: ${{ steps.filesize.outputs.size }}

            ### 📥 Installation:
            1. Download the ZIP file below
            2. Upload to WordPress Admin → Plugins → Add New → Upload Plugin
            3. Activate the plugin

            ### 🔧 Requirements:
            - WordPress 5.0+
            - PHP 8.1+
            - Multisite Network

            **Ready for WordPress.org submission!** ✨
          files: |
            network-site-details-*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
